### ISSUE TITLE
Fetching song_id on newly updated song fails script

### ISSUE THREAD

**Issue by bensteUEM** [bensteUEM/ChurchToolsAPI#26]
```
/home/benste/PycharmProjects/SongBeamerQS/venv/bin/python /home/benste/PycharmProjects/SongBeamerQS/main.py 
Traceback (most recent call last):
  File "/home/benste/PycharmProjects/SongBeamerQS/main.py", line 421, in <module>
    upload_new_local_songs_and_generate_ct_id(df_sng, df_ct)
  File "/home/benste/PycharmProjects/SongBeamerQS/main.py", line 353, in upload_new_local_songs_and_generate_ct_id
    song_id = api.create_song(title=title, songcategory_id=category_id, author=authors,
  File "/home/benste/PycharmProjects/ChurchToolsAPI/ChurchToolsApi.py", line 395, in create_song
    new_id = int(json.loads(response.content)['data'])
KeyError: 'data'

Process finished with exit code 1
```

**Comment by bensteUEM** [comment]
Issue was missing "Veranstaltungen" permission and return of NONE ID on song creation.
